"""empty message

Revision ID: 30089e2dbfe9
Revises: 
Create Date: 2024-10-02 17:55:51.186459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30089e2dbfe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
